spring:
  datasource:
    url : jdbc:mysql://localhost:3306/book_store
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    #database-platform : org.hibernate.dialect.MySQLDialect